# -*- coding: utf-8 -*-
"""01_preProcessing_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDBzqCF9pxhgElGTo4PLu6DwwFvSu24e
"""

"""
🔒 REGRESSION-BASED PREPROCESSING PIPELINE
SpectroFood Apple Maturity Dataset
Predicting Continuous Dry Matter % (No Classification)
"""

import numpy as np
import pandas as pd
import h5py
from scipy.io import loadmat
from sklearn.model_selection import train_test_split
import os
from tqdm import tqdm
import gc

print("=" * 80)
print("SpectroFood Apple Maturity Dataset - REGRESSION Preprocessing Pipeline")
print("=" * 80)

# ============================================================================
# STEP 1: LOAD MATLAB FILE
# ============================================================================
print("\n[1/8] Loading Apple.mat...")
mat_data = loadmat('/content/Apple.mat')

# Extract wavelengths
wavelengths = mat_data['Wavelengths'].flatten()
print(f"  ✓ Loaded {len(wavelengths)} wavelength bands")

# Extract all 240 apple hypercubes
apples = {}
for i in range(1, 241):
    var_name = f'A{i}'
    if var_name in mat_data:
        apples[i-1] = mat_data[var_name]
    else:
        raise ValueError(f"Missing apple {var_name} in MAT file")

print(f"  ✓ Loaded {len(apples)} apple hypercubes")

# ============================================================================
# STEP 2: LOAD GROUND TRUTH CSV (DRY MATTER VALUES)
# ============================================================================
print("\n[2/8] Loading SpectroFood_dataset.csv...")
csv_data = pd.read_csv('/content/SpectroFood_dataset.csv')
csv_data.columns = csv_data.columns.str.strip()

# Build apple_id -> dry_matter mapping
apple_to_dry_matter = {}
for _, row in csv_data.iterrows():
    apple_name = str(row['Apple']).strip()

    if len(apple_name) < 2 or not apple_name[1:].isdigit():
        print(f"⚠️ Skipping invalid apple_name: {apple_name}")
        continue

    apple_id = int(apple_name[1:]) - 1
    apple_to_dry_matter[apple_id] = row['Dry matter']

print(f"  ✓ Loaded dry matter values for {len(apple_to_dry_matter)} apples")
print(f"  ✓ Dry matter range: {min(apple_to_dry_matter.values()):.4f} - {max(apple_to_dry_matter.values()):.4f}")

# Validate all apples have ground truth
missing_ids = set(range(240)) - set(apple_to_dry_matter.keys())
if missing_ids:
    raise ValueError(f"Missing dry matter values for apple IDs: {missing_ids}")

# ============================================================================
# STEP 3: STATISTICS ON DRY MATTER DISTRIBUTION
# ============================================================================
print("\n[3/8] Analyzing dry matter distribution...")

all_dry_matters = np.array([apple_to_dry_matter[aid] for aid in range(240)])

print(f"\n  Dry matter statistics:")
print(f"    Min:  {all_dry_matters.min():.4f}")
print(f"    Max:  {all_dry_matters.max():.4f}")
print(f"    Mean: {all_dry_matters.mean():.4f}")
print(f"    Std:  {all_dry_matters.std():.4f}")
print(f"    Range: {all_dry_matters.max() - all_dry_matters.min():.4f}")

print(f"\n  Dry matter percentiles:")
for p in [10, 25, 50, 75, 90]:
    val = np.percentile(all_dry_matters, p)
    print(f"    {p:2d}%: {val:.4f}")

# ============================================================================
# STEP 4: STRATIFIED TRAIN/TEST SPLIT AT APPLE LEVEL
# ============================================================================
print("\n[4/8] Stratified splitting of apples (80/20)...")

# Create quartile-based bins for stratification
# This ensures similar dry matter distributions in train/test
dry_matter_bins = pd.qcut(all_dry_matters, q=4, labels=False, duplicates='drop')

apple_ids = list(range(240))

train_apple_ids, test_apple_ids = train_test_split(
    apple_ids,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=dry_matter_bins  # Stratify by dry matter quartiles
)

print(f"  ✓ Train apples: {len(train_apple_ids)}")
print(f"  ✓ Test apples: {len(test_apple_ids)}")

# Check dry matter distributions in splits
train_dry_matters = [apple_to_dry_matter[aid] for aid in train_apple_ids]
test_dry_matters = [apple_to_dry_matter[aid] for aid in test_apple_ids]

print(f"\n  Train dry matter distribution:")
print(f"    Mean: {np.mean(train_dry_matters):.4f}, Std: {np.std(train_dry_matters):.4f}")
print(f"    Range: [{np.min(train_dry_matters):.4f}, {np.max(train_dry_matters):.4f}]")

print(f"\n  Test dry matter distribution:")
print(f"    Mean: {np.mean(test_dry_matters):.4f}, Std: {np.std(test_dry_matters):.4f}")
print(f"    Range: [{np.min(test_dry_matters):.4f}, {np.max(test_dry_matters):.4f}]")

# Critical check: no overlap
overlap = set(train_apple_ids) & set(test_apple_ids)
if overlap:
    raise ValueError(f"LEAKAGE DETECTED: Apples {overlap} appear in both splits!")
print(f"\n  ✓ Verified: Zero overlap between train and test apples")

# ============================================================================
# STEP 5: COUNT PATCHES
# ============================================================================
print("\n[5/8] Counting patches per split...")

PATCH_SIZE = 11
HALF_PATCH = PATCH_SIZE // 2

def count_patches_for_apple(apple_cube):
    h, w, bands = apple_cube.shape
    count = 0
    for y in range(HALF_PATCH, h - HALF_PATCH):
        for x in range(HALF_PATCH, w - HALF_PATCH):
            count += 1
    return count

# Count train patches
train_patch_count = 0
for apple_id in tqdm(train_apple_ids, desc="  Counting train patches"):
    train_patch_count += count_patches_for_apple(apples[apple_id])

# Count test patches
test_patch_count = 0
for apple_id in tqdm(test_apple_ids, desc="  Counting test patches"):
    test_patch_count += count_patches_for_apple(apples[apple_id])

print(f"  ✓ Train patches: {train_patch_count:,}")
print(f"  ✓ Test patches: {test_patch_count:,}")

# ============================================================================
# STEP 6: EXTRACT AND SAVE TRAINING DATA
# ============================================================================
print("\n[6/8] Extracting TRAIN patches...")

h5_train = h5py.File('X_spatial_train.h5', 'w')
X_spatial_train_dataset = h5_train.create_dataset(
    'X_spatial',
    shape=(train_patch_count, PATCH_SIZE, PATCH_SIZE, 141),
    dtype=np.float32,
    chunks=(min(1000, train_patch_count), PATCH_SIZE, PATCH_SIZE, 141)
)

X_spectral_train = np.zeros((train_patch_count, 141), dtype=np.float32)
Y_train = np.zeros(train_patch_count, dtype=np.float32)  # Continuous targets!

patch_idx = 0
for apple_id in tqdm(train_apple_ids, desc="  Processing train apples"):
    cube = apples[apple_id].astype(np.float32)
    h, w, bands = cube.shape
    dry_matter = apple_to_dry_matter[apple_id]  # Continuous value

    for y in range(HALF_PATCH, h - HALF_PATCH):
        for x in range(HALF_PATCH, w - HALF_PATCH):
            spatial_patch = cube[y-HALF_PATCH:y+HALF_PATCH+1,
                                 x-HALF_PATCH:x+HALF_PATCH+1, :]
            spectral_vector = cube[y, x, :]

            X_spatial_train_dataset[patch_idx] = spatial_patch
            X_spectral_train[patch_idx] = spectral_vector
            Y_train[patch_idx] = dry_matter  # Store continuous dry matter

            patch_idx += 1

np.save('X_spectral_train.npy', X_spectral_train)
np.save('Y_train.npy', Y_train)

print(f"  ✓ Saved X_spatial_train.h5: shape {X_spatial_train_dataset.shape}")
print(f"  ✓ Saved X_spectral_train.npy: shape {X_spectral_train.shape}")
print(f"  ✓ Saved Y_train.npy: shape {Y_train.shape}")

del X_spectral_train, Y_train
gc.collect()

h5_train.close()

# ============================================================================
# STEP 7: EXTRACT AND SAVE TEST DATA
# ============================================================================
print("\n[7/8] Extracting TEST patches...")

h5_test = h5py.File('X_spatial_test.h5', 'w')
X_spatial_test_dataset = h5_test.create_dataset(
    'X_spatial',
    shape=(test_patch_count, PATCH_SIZE, PATCH_SIZE, 141),
    dtype=np.float32,
    chunks=(min(1000, test_patch_count), PATCH_SIZE, PATCH_SIZE, 141)
)

X_spectral_test = np.zeros((test_patch_count, 141), dtype=np.float32)
Y_test = np.zeros(test_patch_count, dtype=np.float32)  # Continuous targets!

patch_idx = 0
for apple_id in tqdm(test_apple_ids, desc="  Processing test apples"):
    cube = apples[apple_id].astype(np.float32)
    h, w, bands = cube.shape
    dry_matter = apple_to_dry_matter[apple_id]  # Continuous value

    for y in range(HALF_PATCH, h - HALF_PATCH):
        for x in range(HALF_PATCH, w - HALF_PATCH):
            spatial_patch = cube[y-HALF_PATCH:y+HALF_PATCH+1,
                                 x-HALF_PATCH:x+HALF_PATCH+1, :]
            spectral_vector = cube[y, x, :]

            X_spatial_test_dataset[patch_idx] = spatial_patch
            X_spectral_test[patch_idx] = spectral_vector
            Y_test[patch_idx] = dry_matter  # Store continuous dry matter

            patch_idx += 1

np.save('X_spectral_test.npy', X_spectral_test)
np.save('Y_test.npy', Y_test)

print(f"  ✓ Saved X_spatial_test.h5: shape {X_spatial_test_dataset.shape}")
print(f"  ✓ Saved X_spectral_test.npy: shape {X_spectral_test.shape}")
print(f"  ✓ Saved Y_test.npy: shape {Y_test.shape}")

h5_test.close()

# ============================================================================
# STEP 8: FINAL VALIDATION
# ============================================================================
print("\n[8/8] Final Validation Checks...")
print("=" * 80)

Y_train = np.load('Y_train.npy')
Y_test = np.load('Y_test.npy')

# Apple-level statistics
print("\n📊 APPLE-LEVEL STATISTICS:")
print(f"  • Total apples: 240")
print(f"  • Train apples: {len(train_apple_ids)} ({len(train_apple_ids)/240*100:.1f}%)")
print(f"  • Test apples: {len(test_apple_ids)} ({len(test_apple_ids)/240*100:.1f}%)")

# Patch-level statistics
print(f"\n📊 PATCH-LEVEL STATISTICS:")
print(f"  • Train patches: {train_patch_count:,}")
print(f"  • Test patches: {test_patch_count:,}")
print(f"  • Total patches: {train_patch_count + test_patch_count:,}")

# Target distributions
print(f"\n📊 TARGET DISTRIBUTION (Continuous):")
print(f"  Train:")
print(f"    Mean: {Y_train.mean():.6f}")
print(f"    Std:  {Y_train.std():.6f}")
print(f"    Range: [{Y_train.min():.6f}, {Y_train.max():.6f}]")
print(f"\n  Test:")
print(f"    Mean: {Y_test.mean():.6f}")
print(f"    Std:  {Y_test.std():.6f}")
print(f"    Range: [{Y_test.min():.6f}, {Y_test.max():.6f}]")

# Check distribution similarity
mean_diff = abs(Y_train.mean() - Y_test.mean())
std_diff = abs(Y_train.std() - Y_test.std())

print(f"\n📊 DISTRIBUTION SIMILARITY:")
print(f"  • Mean difference: {mean_diff:.6f}")
print(f"  • Std difference: {std_diff:.6f}")
if mean_diff < 0.002 and std_diff < 0.002:
    print(f"  ✓ Distributions are very similar")
else:
    print(f"  ⚠️  Distributions differ slightly")

# Critical leakage check
print(f"\n🔒 LEAKAGE VALIDATION:")
overlap_check = set(train_apple_ids) & set(test_apple_ids)
if overlap_check:
    print(f"  ❌ FAILURE: Apple IDs {overlap_check} appear in both splits!")
    raise ValueError("DATA LEAKAGE DETECTED")
else:
    print(f"  ✅ VERIFIED: No apple appears in both train and test splits")
    print(f"  ✅ VERIFIED: {len(set(train_apple_ids) | set(test_apple_ids))} unique apples total")

# File existence check
print(f"\n📁 OUTPUT FILES:")
expected_files = [
    'X_spatial_train.h5',
    'X_spatial_test.h5',
    'X_spectral_train.npy',
    'X_spectral_test.npy',
    'Y_train.npy',
    'Y_test.npy'
]
for fname in expected_files:
    if os.path.exists(fname):
        size_mb = os.path.getsize(fname) / (1024**2)
        print(f"  ✓ {fname} ({size_mb:.1f} MB)")
    else:
        print(f"  ✗ {fname} MISSING!")

print("\n" + "=" * 80)
print("✅ PREPROCESSING COMPLETE - REGRESSION DATASET READY")
print("=" * 80)

# ============================================================================
# UPLOAD TO GCS
# ============================================================================
from google.colab import auth
auth.authenticate_user()

GCS_BUCKET = 'processed_data-iyed'
GCS_PREFIX = 'processed_regression'

files_to_upload = [
    'X_spatial_train.h5',
    'X_spatial_test.h5',
    'X_spectral_train.npy',
    'X_spectral_test.npy',
    'Y_train.npy',
    'Y_test.npy'
]

parallel_upload_threshold = '150M'

print(f"\nUploading files to gs://{GCS_BUCKET}/{GCS_PREFIX}/...\n")

for file_path in files_to_upload:
    gsutil_command = (
        f"gsutil -o GSUtil:parallel_composite_upload_threshold={parallel_upload_threshold} cp "
        f"{file_path} gs://{GCS_BUCKET}/{GCS_PREFIX}/"
    )
    print(f"Uploading {file_path}...")
    get_ipython().system(gsutil_command)

print("\n✅ ALL FILES UPLOADED TO GCS SUCCESSFULLY")