# -*- coding: utf-8 -*-
"""02_training_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilxF95qjof6K_AuO2TB7xtkK9pX6dNQ2
"""

"""
🔒 REGRESSION-BASED TRAINING PIPELINE
SpectroFood Apple Maturity Classification
Hybrid CNN + Transformer - Predicting Continuous Dry Matter %
"""

import os
import numpy as np
import pandas as pd
import h5py
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Tuple, Dict, List
import json

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model, callbacks
from tensorflow.keras.utils import Sequence
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from google.cloud import storage

print("=" * 80)
print("SpectroFood Apple Maturity - Hybrid CNN+Transformer REGRESSION Training")
print("=" * 80)
print(f"TensorFlow Version: {tf.__version__}")
print(f"GPU Available: {tf.config.list_physical_devices('GPU')}")

# ============================================================================
# CONFIGURATION
# ============================================================================
class Config:
    """Training configuration"""
    # GCS Settings
    GCS_BUCKET = "processed_data-iyed"
    GCS_PREFIX = "processed_regression/"  # NOTE: Updated prefix

    # Data files
    SPATIAL_TRAIN = "X_spatial_train.h5"
    SPATIAL_TEST = "X_spatial_test.h5"
    SPECTRAL_TRAIN = "X_spectral_train.npy"
    SPECTRAL_TEST = "X_spectral_test.npy"
    LABELS_TRAIN = "Y_train.npy"
    LABELS_TEST = "Y_test.npy"

    # Model parameters
    SPATIAL_SHAPE = (11, 11, 141)
    SPECTRAL_SHAPE = (141,)
    OUTPUT_DIM = 1  # Single continuous output

    # Training parameters
    BATCH_SIZE = 64
    EPOCHS = 100
    LEARNING_RATE = 1e-4
    WEIGHT_DECAY = 1e-5

    # CNN parameters
    CNN_FILTERS = [32, 64, 128, 256]
    CNN_DROPOUT = 0.3

    # Transformer parameters
    TRANSFORMER_HEADS = 8
    TRANSFORMER_LAYERS = 3
    TRANSFORMER_DIM = 128
    TRANSFORMER_FF_DIM = 256

    # Fusion parameters
    FUSION_DIM = 256

    # Classifier parameters
    CLASSIFIER_DIMS = [512, 256, 128]
    CLASSIFIER_DROPOUT = 0.4

    # Callbacks
    EARLY_STOPPING_PATIENCE = 15
    REDUCE_LR_PATIENCE = 8

    # Paths
    CHECKPOINT_DIR = "checkpoints"
    RESULTS_DIR = "results"

config = Config()

# Create directories
os.makedirs(config.CHECKPOINT_DIR, exist_ok=True)
os.makedirs(config.RESULTS_DIR, exist_ok=True)

# ============================================================================
# GCS AUTHENTICATION & DATA DOWNLOAD
# ============================================================================
print("\n[1/10] Setting up GCS and downloading data...")

from google.colab import auth
auth.authenticate_user()

storage_client = storage.Client()
bucket = storage_client.bucket(config.GCS_BUCKET)

def download_from_gcs(gcs_path: str, local_path: str) -> None:
    """Download file from GCS to local storage"""
    blob = bucket.blob(gcs_path)
    blob.download_to_filename(local_path)
    size_mb = os.path.getsize(local_path) / (1024**2)
    print(f"  ✓ Downloaded {local_path} ({size_mb:.1f} MB)")

files_to_download = [
    (config.GCS_PREFIX + config.SPATIAL_TRAIN, config.SPATIAL_TRAIN),
    (config.GCS_PREFIX + config.SPATIAL_TEST, config.SPATIAL_TEST),
    (config.GCS_PREFIX + config.SPECTRAL_TRAIN, config.SPECTRAL_TRAIN),
    (config.GCS_PREFIX + config.SPECTRAL_TEST, config.SPECTRAL_TEST),
    (config.GCS_PREFIX + config.LABELS_TRAIN, config.LABELS_TRAIN),
    (config.GCS_PREFIX + config.LABELS_TEST, config.LABELS_TEST),
]

for gcs_path, local_path in files_to_download:
    download_from_gcs(gcs_path, local_path)

# ============================================================================
# DATA INSPECTION
# ============================================================================
print("\n[2/10] Inspecting downloaded data...")

X_spectral_train = np.load(config.SPECTRAL_TRAIN)
X_spectral_test = np.load(config.SPECTRAL_TEST)
Y_train = np.load(config.LABELS_TRAIN)
Y_test = np.load(config.LABELS_TEST)

with h5py.File(config.SPATIAL_TRAIN, 'r') as f:
    spatial_train_shape = f['X_spatial'].shape
    print(f"  ✓ Train spatial: {spatial_train_shape}")

with h5py.File(config.SPATIAL_TEST, 'r') as f:
    spatial_test_shape = f['X_spatial'].shape
    print(f"  ✓ Test spatial: {spatial_test_shape}")

print(f"  ✓ Train spectral: {X_spectral_train.shape}")
print(f"  ✓ Test spectral: {X_spectral_test.shape}")
print(f"  ✓ Train labels: {Y_train.shape}")
print(f"  ✓ Test labels: {Y_test.shape}")

assert spatial_train_shape[0] == X_spectral_train.shape[0] == Y_train.shape[0], "Train data misalignment!"
assert spatial_test_shape[0] == X_spectral_test.shape[0] == Y_test.shape[0], "Test data misalignment!"
print(f"  ✓ Data alignment verified")

print(f"\n  Train target (dry matter) distribution:")
print(f"    Mean: {Y_train.mean():.6f}, Std: {Y_train.std():.6f}")
print(f"    Range: [{Y_train.min():.6f}, {Y_train.max():.6f}]")

print(f"\n  Test target (dry matter) distribution:")
print(f"    Mean: {Y_test.mean():.6f}, Std: {Y_test.std():.6f}")
print(f"    Range: [{Y_test.min():.6f}, {Y_test.max():.6f}]")

# ============================================================================
# CUSTOM DATA GENERATOR FOR REGRESSION
# ============================================================================
print("\n[3/10] Creating custom data generators...")

class HybridDataGenerator(Sequence):
    """Memory-efficient data generator for hybrid spatial + spectral data (REGRESSION)"""

    def __init__(self,
                 spatial_h5_path: str,
                 spectral_array: np.ndarray,
                 labels: np.ndarray,
                 batch_size: int = 32,
                 shuffle: bool = True,
                 augment: bool = False):
        self.spatial_h5_path = spatial_h5_path
        self.spectral_array = spectral_array
        self.labels = labels
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.augment = augment

        self.spatial_file = h5py.File(spatial_h5_path, 'r')
        self.spatial_dataset = self.spatial_file['X_spatial']

        self.n_samples = len(spectral_array)
        self.indices = np.arange(self.n_samples)

        self._compute_normalization_params()
        self.on_epoch_end()

    def _compute_normalization_params(self):
        """Compute normalization parameters"""
        sample_size = min(1000, self.n_samples)
        sample_indices = np.random.choice(self.n_samples, sample_size, replace=False)
        sample_indices = np.sort(sample_indices)

        spatial_sample = self.spatial_dataset[sample_indices]
        self.spatial_min = spatial_sample.min()
        self.spatial_max = spatial_sample.max()

        self.spectral_min = self.spectral_array.min()
        self.spectral_max = self.spectral_array.max()

        self.label_min = self.labels.min()
        self.label_max = self.labels.max()

    def __len__(self) -> int:
        return int(np.ceil(self.n_samples / self.batch_size))

    def __getitem__(self, index: int) -> Tuple[Dict[str, np.ndarray], np.ndarray]:
        start_idx = index * self.batch_size
        end_idx = min((index + 1) * self.batch_size, self.n_samples)
        batch_indices = self.indices[start_idx:end_idx]

        sorted_positions = np.argsort(batch_indices)
        sorted_indices = batch_indices[sorted_positions]

        spatial_batch = self.spatial_dataset[sorted_indices]
        spatial_batch = spatial_batch[np.argsort(sorted_positions)]

        spectral_batch = self.spectral_array[batch_indices]
        labels_batch = self.labels[batch_indices]

        spatial_batch = (spatial_batch - self.spatial_min) / (self.spatial_max - self.spatial_min + 1e-8)
        spectral_batch = (spectral_batch - self.spectral_min) / (self.spectral_max - self.spectral_min + 1e-8)
        labels_batch = (labels_batch - self.label_min) / (self.label_max - self.label_min + 1e-8)

        if self.augment:
            spatial_batch, spectral_batch = self._augment(spatial_batch, spectral_batch)

        return {
            'spatial_input': spatial_batch.astype(np.float32),
            'spectral_input': spectral_batch.astype(np.float32)
        }, labels_batch.reshape(-1, 1).astype(np.float32)

    def _augment(self, spatial: np.ndarray, spectral: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Data augmentation"""
        for i in range(spatial.shape[0]):
            if np.random.rand() > 0.5:
                spatial[i] = np.flip(spatial[i], axis=0)
            if np.random.rand() > 0.5:
                spatial[i] = np.flip(spatial[i], axis=1)
            if np.random.rand() > 0.75:
                k = np.random.randint(1, 4)
                spatial[i] = np.rot90(spatial[i], k=k, axes=(0, 1))

        noise = np.random.normal(0, 0.01, spectral.shape)
        spectral = spectral + noise
        scale_factor = np.random.uniform(0.95, 1.05, size=(spectral.shape[0], 1))
        spectral = spectral * scale_factor
        spectral = np.clip(spectral, 0, 1)

        return spatial, spectral

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

    def __del__(self):
        if hasattr(self, 'spatial_file'):
            self.spatial_file.close()

train_generator = HybridDataGenerator(
    config.SPATIAL_TRAIN,
    X_spectral_train,
    Y_train,
    batch_size=config.BATCH_SIZE,
    shuffle=True,
    augment=True
)

val_generator = HybridDataGenerator(
    config.SPATIAL_TEST,
    X_spectral_test,
    Y_test,
    batch_size=config.BATCH_SIZE,
    shuffle=False,
    augment=False
)

print(f"  ✓ Train generator: {len(train_generator)} batches")
print(f"  ✓ Val generator: {len(val_generator)} batches")

# ============================================================================
# MODEL ARCHITECTURE
# ============================================================================
print("\n[4/10] Building hybrid CNN + Transformer model...")

def create_spatial_cnn_branch(input_shape: Tuple[int, int, int]) -> Model:
    inputs = layers.Input(shape=input_shape, name='spatial_input')
    x = inputs

    for i, filters in enumerate(config.CNN_FILTERS):
        x = layers.Conv2D(filters, (3, 3), padding='same', name=f'cnn_conv_{i}')(x)
        x = layers.BatchNormalization(name=f'cnn_bn_{i}')(x)
        x = layers.Activation('relu', name=f'cnn_relu_{i}')(x)
        if i > 0:
            x = layers.Dropout(config.CNN_DROPOUT, name=f'cnn_dropout_{i}')(x)

    x = layers.GlobalAveragePooling2D(name='cnn_gap')(x)
    spatial_features = layers.Dense(config.FUSION_DIM, activation='relu', name='spatial_features')(x)

    return Model(inputs=inputs, outputs=spatial_features, name='spatial_cnn_branch')

def positional_encoding(length: int, depth: int) -> np.ndarray:
    positions = np.arange(length)[:, np.newaxis]
    depths = np.arange(depth)[np.newaxis, :] / depth
    angle_rates = 1 / (10000**depths)
    angle_rads = positions * angle_rates
    pos_encoding = np.concatenate([np.sin(angle_rads), np.cos(angle_rads)], axis=-1)
    return pos_encoding[:, :depth].astype(np.float32)

class TransformerEncoderBlock(layers.Layer):
    def __init__(self, d_model: int, num_heads: int, ff_dim: int, dropout: float = 0.1, **kwargs):
        super().__init__(**kwargs)
        self.d_model = d_model
        self.num_heads = num_heads
        self.ff_dim = ff_dim
        self.dropout_rate = dropout

        self.mha = layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.ffn = keras.Sequential([
            layers.Dense(ff_dim, activation='relu'),
            layers.Dense(d_model),
        ])

        self.layernorm1 = layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(dropout)
        self.dropout2 = layers.Dropout(dropout)

    def call(self, inputs, training=False):
        attn_output = self.mha(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        out2 = self.layernorm2(out1 + ffn_output)

        return out2

    def get_config(self):
        config = super().get_config()
        config.update({
            "d_model": self.d_model,
            "num_heads": self.num_heads,
            "ff_dim": self.ff_dim,
            "dropout": self.dropout_rate
        })
        return config

def create_spectral_transformer_branch(input_shape: Tuple[int,]) -> Model:
    inputs = layers.Input(shape=input_shape, name='spectral_input')
    x = layers.Dense(config.TRANSFORMER_DIM, name='spectral_projection')(inputs)
    x = layers.Reshape((1, config.TRANSFORMER_DIM))(x)

    pos_encoding = positional_encoding(1, config.TRANSFORMER_DIM)
    x = layers.Add()([x, pos_encoding])

    for i in range(config.TRANSFORMER_LAYERS):
        x = TransformerEncoderBlock(
            d_model=config.TRANSFORMER_DIM,
            num_heads=config.TRANSFORMER_HEADS,
            ff_dim=config.TRANSFORMER_FF_DIM,
            dropout=0.1,
            name=f'transformer_block_{i}'
        )(x)

    x = layers.GlobalAveragePooling1D(name='transformer_gap')(x)
    spectral_features = layers.Dense(config.FUSION_DIM, activation='relu', name='spectral_features')(x)

    return Model(inputs=inputs, outputs=spectral_features, name='spectral_transformer_branch')

class AttentionFusion(layers.Layer):
    def __init__(self, fusion_dim: int, **kwargs):
        super().__init__(**kwargs)
        self.fusion_dim = fusion_dim

        self.query_dense = layers.Dense(fusion_dim)
        self.key_dense = layers.Dense(fusion_dim)
        self.value_dense = layers.Dense(fusion_dim)
        self.output_dense = layers.Dense(fusion_dim)
        self.layernorm = layers.LayerNormalization(epsilon=1e-6)

        self.reshape_spatial = layers.Reshape((1, fusion_dim))
        self.reshape_spectral = layers.Reshape((1, fusion_dim))

    def call(self, spatial_features, spectral_features):
        spatial_expanded = self.reshape_spatial(spatial_features)
        spectral_expanded = self.reshape_spectral(spectral_features)

        combined = layers.Concatenate(axis=1)([spatial_expanded, spectral_expanded])

        query = self.query_dense(combined)
        key = self.key_dense(combined)
        value = self.value_dense(combined)

        scores = tf.matmul(query, key, transpose_b=True)
        scores = scores / tf.sqrt(tf.cast(self.fusion_dim, tf.float32))
        attention_weights = tf.nn.softmax(scores, axis=-1)

        attended = tf.matmul(attention_weights, value)
        fused = tf.reduce_mean(attended, axis=1)

        output = self.output_dense(fused)
        output = self.layernorm(output)

        return output

    def get_config(self):
        config = super().get_config()
        config.update({"fusion_dim": self.fusion_dim})
        return config

def create_hybrid_model() -> Model:
    """Create hybrid model for REGRESSION"""
    spatial_branch = create_spatial_cnn_branch(config.SPATIAL_SHAPE)
    spectral_branch = create_spectral_transformer_branch(config.SPECTRAL_SHAPE)

    spatial_input = layers.Input(shape=config.SPATIAL_SHAPE, name='spatial_input')
    spectral_input = layers.Input(shape=config.SPECTRAL_SHAPE, name='spectral_input')

    spatial_features = spatial_branch(spatial_input)
    spectral_features = spectral_branch(spectral_input)

    fused_features = AttentionFusion(config.FUSION_DIM, name='attention_fusion')(
        spatial_features, spectral_features
    )

    x = fused_features
    for i, dim in enumerate(config.CLASSIFIER_DIMS):
        x = layers.Dense(dim, activation='relu', name=f'regressor_dense_{i}')(x)
        x = layers.Dropout(config.CLASSIFIER_DROPOUT, name=f'regressor_dropout_{i}')(x)

    # REGRESSION OUTPUT: Single neuron with linear activation
    outputs = layers.Dense(1, activation='linear', name='output')(x)

    model = Model(
        inputs=[spatial_input, spectral_input],
        outputs=outputs,
        name='hybrid_cnn_transformer_regression'
    )

    return model

model = create_hybrid_model()
model.summary()

print(f"  ✓ Model created with {model.count_params():,} parameters")

# ============================================================================
# COMPILE MODEL FOR REGRESSION
# ============================================================================
print("\n[5/10] Compiling model...")

optimizer = keras.optimizers.AdamW(
    learning_rate=config.LEARNING_RATE,
    weight_decay=config.WEIGHT_DECAY
)

model.compile(
    optimizer=optimizer,
    loss='mse',  # Mean Squared Error for regression
    metrics=[
        'mae',  # Mean Absolute Error
        keras.metrics.RootMeanSquaredError(name='rmse')
    ]
)

print(f"  ✓ Optimizer: AdamW (LR={config.LEARNING_RATE}, WD={config.WEIGHT_DECAY})")
print(f"  ✓ Loss: Mean Squared Error (MSE)")
print(f"  ✓ Metrics: MAE, RMSE")

# ============================================================================
# CALLBACKS
# ============================================================================
print("\n[6/10] Setting up callbacks...")

callback_list = [
    callbacks.ModelCheckpoint(
        filepath=os.path.join(config.CHECKPOINT_DIR, 'best_model.h5'),
        monitor='val_mae',
        mode='min',
        save_best_only=True,
        verbose=1
    ),

    callbacks.EarlyStopping(
        monitor='val_mae',
        mode='min',
        patience=config.EARLY_STOPPING_PATIENCE,
        restore_best_weights=True,
        verbose=1
    ),

    callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        mode='min',
        factor=0.5,
        patience=config.REDUCE_LR_PATIENCE,
        min_lr=1e-7,
        verbose=1
    ),

    callbacks.CSVLogger(
        os.path.join(config.RESULTS_DIR, 'training_log.csv')
    ),

    callbacks.TensorBoard(
        log_dir=os.path.join(config.RESULTS_DIR, 'logs'),
        histogram_freq=1
    )
]

print(f"  ✓ {len(callback_list)} callbacks configured")

# ============================================================================
# TRAINING
# ============================================================================
print("\n[7/10] Starting training...")
print("=" * 80)

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=config.EPOCHS,
    callbacks=callback_list,
    verbose=1
)

print("=" * 80)
print("  ✓ Training complete!")

model.save(os.path.join(config.RESULTS_DIR, 'final_model.h5'))
print(f"  ✓ Final model saved")

with open(os.path.join(config.RESULTS_DIR, 'history.json'), 'w') as f:
    json.dump(history.history, f, indent=2)

# ============================================================================
# EVALUATION
# ============================================================================
print("\n[8/10] Evaluating on test set...")

best_model = keras.models.load_model(
    os.path.join(config.CHECKPOINT_DIR, 'best_model.h5'),
    custom_objects={
        'TransformerEncoderBlock': TransformerEncoderBlock,
        'AttentionFusion': AttentionFusion
    }
)

test_loss, test_mae, test_rmse = best_model.evaluate(val_generator, verbose=1)

print(f"\n  Test Loss (MSE): {test_loss:.8f}")
print(f"  Test MAE: {test_mae:.8f}")
print(f"  Test RMSE: {test_rmse:.8f}")

# Generate predictions
print("\n  Generating predictions...")
y_pred_norm = best_model.predict(val_generator, verbose=1)

# Denormalize predictions and targets
y_pred = y_pred_norm.flatten() * (val_generator.label_max - val_generator.label_min) + val_generator.label_min
y_true = Y_test  # Already in original scale

# Compute metrics on original scale
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print(f"\n  Regression Metrics (Original Scale):")
print(f"    MAE:  {mae:.6f} (dry matter units)")
print(f"    RMSE: {rmse:.6f}")
print(f"    R²:   {r2:.4f}")

# Optional: Convert to 3-class classification for comparison
def classify_prediction(dry_matter):
    """Convert dry matter to 3 classes (for comparison only)"""
    if dry_matter < 0.1516:
        return 0
    elif dry_matter < 0.1594:
        return 1
    else:
        return 2

y_pred_class = np.array([classify_prediction(dm) for dm in y_pred])
y_true_class = np.array([classify_prediction(dm) for dm in y_true])

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
acc = accuracy_score(y_true_class, y_pred_class)

print(f"\n  Classification Accuracy (derived from regression): {acc:.4f}")
print("\n  Classification Report:")
print(classification_report(
    y_true_class,
    y_pred_class,
    target_names=['Unripe', 'Medium', 'Ripe'],
    digits=4
))

# ============================================================================
# VISUALIZATION
# ============================================================================
print("\n[9/10] Creating visualizations...")

# Training curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['loss'], label='Train Loss (MSE)', linewidth=2)
axes[0].plot(history.history['val_loss'], label='Val Loss (MSE)', linewidth=2)
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss (MSE)', fontsize=12)
axes[0].set_title('Training and Validation Loss', fontsize=14, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].grid(alpha=0.3)

axes[1].plot(history.history['mae'], label='Train MAE', linewidth=2)
axes[1].plot(history.history['val_mae'], label='Val MAE', linewidth=2)
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('MAE', fontsize=12)
axes[1].set_title('Training and Validation MAE', fontsize=14, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(config.RESULTS_DIR, 'training_curves.png'), dpi=300, bbox_inches='tight')
plt.show()
print("  ✓ Training curves saved")

# Scatter plot: predicted vs actual
plt.figure(figsize=(10, 8))
plt.scatter(y_true, y_pred, alpha=0.5, s=20)
plt.plot([y_true.min(), y_true.max()],
         [y_true.min(), y_true.max()],
         'r--', lw=2, label='Perfect Prediction')
plt.xlabel('True Dry Matter %', fontsize=12)
plt.ylabel('Predicted Dry Matter %', fontsize=12)
plt.title(f'Regression Performance\nR²={r2:.3f}, MAE={mae:.6f}, RMSE={rmse:.6f}',
          fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(config.RESULTS_DIR, 'regression_scatter.png'), dpi=300, bbox_inches='tight')
plt.show()
print("  ✓ Scatter plot saved")

# Residual plot
residuals = y_pred - y_true
plt.figure(figsize=(10, 6))
plt.scatter(y_pred, residuals, alpha=0.5, s=20)
plt.axhline(y=0, color='r', linestyle='--', lw=2)
plt.xlabel('Predicted Dry Matter %', fontsize=12)
plt.ylabel('Residuals', fontsize=12)
plt.title('Residual Plot', fontsize=14, fontweight='bold')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(config.RESULTS_DIR, 'regression_residuals.png'), dpi=300, bbox_inches='tight')
plt.show()
print("  ✓ Residual plot saved")

# Confusion matrix (for classification comparison)
cm = confusion_matrix(y_true_class, y_pred_class)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Unripe', 'Medium', 'Ripe'],
            yticklabels=['Unripe', 'Medium', 'Ripe'],
            cbar_kws={'label': 'Count'})
axes[0].set_xlabel('Predicted', fontsize=12)
axes[0].set_ylabel('True', fontsize=12)
axes[0].set_title('Confusion Matrix (Counts)', fontsize=14, fontweight='bold')

sns.heatmap(cm_normalized, annot=True, fmt='.2%', cmap='Greens', ax=axes[1],
            xticklabels=['Unripe', 'Medium', 'Ripe'],
            yticklabels=['Unripe', 'Medium', 'Ripe'],
            cbar_kws={'label': 'Percentage'})
axes[1].set_xlabel('Predicted', fontsize=12)
axes[1].set_ylabel('True', fontsize=12)
axes[1].set_title('Confusion Matrix (Normalized)', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig(os.path.join(config.RESULTS_DIR, 'confusion_matrix_from_regression.png'), dpi=300, bbox_inches='tight')
plt.show()
print("  ✓ Confusion matrix saved")

# ============================================================================
# FINAL SUMMARY
# ============================================================================
print("\n[10/10] Training Summary")
print("=" * 80)
print(f"✅ Best Validation MAE: {min(history.history['val_mae']):.8f}")
print(f"✅ Final Test MAE: {mae:.6f}")
print(f"✅ Final Test RMSE: {rmse:.6f}")
print(f"✅ R² Score: {r2:.4f}")
print(f"✅ Classification Accuracy (derived): {acc:.4f}")
print(f"✅ Total Epochs: {len(history.history['loss'])}")
print(f"✅ Total Parameters: {model.count_params():,}")
print("\n📁 Saved Files:")
print(f"  • {os.path.join(config.CHECKPOINT_DIR, 'best_model.h5')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'final_model.h5')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'training_log.csv')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'history.json')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'training_curves.png')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'regression_scatter.png')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'regression_residuals.png')}")
print(f"  • {os.path.join(config.RESULTS_DIR, 'confusion_matrix_from_regression.png')}")
print("=" * 80)
print("🎉 REGRESSION TRAINING PIPELINE COMPLETE!")
print("=" * 80)